```{r}
 library(wehoop)
library(tidyverse)
```

```{r}

teams <- espn_wbb_teams(2023 )
```


loading data from derek
```{r}

teams <- read_csv("data/teams.csv")

```

23-24 Tournament teams list 
******* needs to be updated with this year's tournament field ******

** Note that spellings may be different from Derek's list to how I typed it. Check abbreviations... st.***


```{r}
teams_23_24 <- c("Maine", "Rice", "Richmond", "Notre Dame", "Florida Gulf Coast", "Texas", "UConn", "Eastern Washington", "Presbyterian", "Iowa", "UC Irvine", "Drexel", "Middle Tennessee", "Green Bay", "Princeton", "Fairfield", "Kent State", "Norfolk State", "Drake", "UNLV", "Sacred Heart", "UT Martin", "Southern Cal", "Holy Cross", "South Carolina", "Chattanooga", "A&M-Corpus Christi", "Jackson St.", "South Dakota State", "Marshall", "Portland", "California Baptist")
```

------ Data Exploration ---------

- State and conference counts.

```{r}

state_counts <- teams %>% 
  filter(team %in% teams_23_24) %>% 
  group_by(team_state) %>% 
  summarize(state_counts = n()) %>%   
  arrange(desc(state_counts))

```
Conference counts
```{r}

conf_counts <- teams %>% 
  filter(team %in% teams_23_24) %>% 
  group_by(conference) %>% 
  summarize(conf_counts = n()) %>%   
  arrange(desc(conf_counts))

```






